# Generated by Django 3.2.2 on 2021-05-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('tmax', models.IntegerField()),
                ('tmin', models.IntegerField()),
                ('rainfall', models.IntegerField()),
            ],
        ),
    ]
