# Generated by Django 3.2.2 on 2021-05-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='rainfall',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='tmax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='tmin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
