# Generated by Django 3.2.2 on 2021-05-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210507_1932'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together={('location', 'date')},
        ),
    ]
