# Generated by Django 3.2.2 on 2021-05-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_weather_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='rainfall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='tmax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='tmin',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
