# Generated by Django 3.2.2 on 2021-05-10 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210510_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='weather',
            name='metric',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.metric'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weather',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together={('location', 'date', 'metric')},
        ),
        migrations.RemoveField(
            model_name='weather',
            name='rainfall',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='tmax',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='tmin',
        ),
    ]
