# Generated by Django 3.2.2 on 2021-05-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210510_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='value',
            field=models.FloatField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
